### ISSUE TITLE
Workflow failed: No filenames specified!

### ISSUE THREAD

**Issue by jayvdb** [Swatinem/fucov#5]
My YAML is using just the defaults.  I am running it locally using https://github.com/nektos/act but I dont see how that could be the problem.

```yaml
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # coverage action needs a nightly toolchain with llvm-tools
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview

      # runs cargo with defaults flags, using the default `lcov` output
      - uses: Swatinem/fucov@v1
```

```
|     Finished test [unoptimized + debuginfo] target(s) in 1m 58s
|      Running unittests src/main.rs (target/debug/deps/cargo_test_xunit-124fad530140ef78)
| 
| running 1 test
| test parser::tests::parse_output ... ok
| 
| test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
| 
| [command]/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata merge -sparse /tmp/_profraw/344-2690798127844891782_0.profraw /tmp/_profraw/348-7005446241495356693_0.profraw /tmp/_profraw/488-11968602179188622136_0.profraw -o /tmp/_profraw/coverage.profdata-1
| [command]/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-cov export -format=lcov -ignore-filename-regex=([\/]rustc[\/]|[\/].cargo[\/]registry[\/]) -instr-profile=/tmp/_profraw/coverage.profdata
| No filenames specified!
[Test/Test]   ❗  ::error::Error: The process '/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-cov' failed with exit code 1
```

I've switched to using https://github.com/actions-rs/grcov which works for my needs.
https://github.com/jayvdb/cargo-test-xunit/blob/master/.github/workflows/test.yml#L29
